### ISSUE TITLE
1.0 MVP Release

### ISSUE THREAD

**Issue by john-g-g** [steemit/yo#113]
# Issues
- [] #52 Import email templates from sendgrid
- [] #111 Implement blockchain follower coordination in database
- [] #105 Incorrect result counting in get_priorty_count
- [] #100 Fix query in notification sender for run_notifications
- [] #97 Basic functionality: ensure each type of notification triggers transports
- [] #112 Add SMS message templates
- [] #110 Fix rate limits
- [] #108 Request the user's phone number from steemit api to send sms using signed request
- [] #109 Request the user's email address from steemit api using signed request

**Comment by GarethNelson** [comment]
#100 should be good

**Comment by relativityboy** [comment]
RE: #108  #109 https://github.com/steemit/conveyor/pull/23/files
Is there only one phone/email per user in steemit api (conveyor)?

**Comment by relativityboy** [comment]
Clarified in a conversation w/ @sneak clarified that yo will use the account email and phone stored elsewhere.
