### ISSUE TITLE
Pseudo roadmap for yo

### ISSUE THREAD

**Issue by GarethNelson** [steemit/yo#65]
Please feel free to add items to this checklist as appropriate, we'll use it to track the current toplevel priorities.

- [ ] Immediate priority: fully working notifications in condenser
- [ ] Immediately priority: multiple instance support for all components
- [ ] Medium term priority: email transport
- [ ] Post-steemfest: SMS, VAPID, APNS, Firebase et al

Some commentary on the above and current status:
I've been working myself almost exclusively on the polled API for condenser and this is where progress is most advanced, but there are lots of little things going on and too many to list here.

Email transport: the transport code exists, it needs templates imported and some logic to choose the right template based on notification type. This is being tracked in issue #52 currently assigned to @jnordberg 

Multiple instance support: theoretically, if we run 2 or more instances right now, the API server will do fine, but there's no support for multiple blockchain followers keeping in sync with each other to avoid duplicate notifications. Earlier today I actually dropped the DB table used for this, but basically the approach is the one outlined here: https://github.com/steemit/yo/issues/64

After the scaling issues are sorted or at least more reliable we can start adding more transports - naturally reliability comes first.

Longer term we have stuff like localisation, please add such items to this issue so we can keep track of general overall vision.

**Comment by goldibex** [comment]
Who set these priorities?

**Comment by GarethNelson** [comment]
Arised out of discussions on slack with @john-g-g and others.

Of course the above can easily be changed, please advise.

Sneak has said multiple instance support is needed for MVP, so more attention needs to be paid to that now and i'd like to know if we can start with multiple API servers to begin with

**Comment by GarethNelson** [comment]
Closing to keep stuff clean based on new methodology
